version: '3.3'
services:
  vote-gateway:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-gateway
    image: vote-gateway:1.0
    restart: always
    container_name: vote-gateway
    ports:
      - "8080:8080"

  vote-auth:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-auth
    image: vote-auth:1.0
    restart: always
    container_name: vote-auth
    ports:
      - "10000:10000"

  vote-oss:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-oss
    image: vote-oss:1.0
    restart: always
    container_name: vote-oss
    ports:
      - "9000:9000"

  vote-modules-permission:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-permission
    image: vote-modules-permission:1.0
    restart: always
    container_name: vote-modules-permission
    ports:
      - "9202:9202"

  vote-modules-vote:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-vote
    image: vote-modules-vote:1.0
    restart: always
    container_name: vote-modules-vote
    ports:
      - "9201:9201"

