spring:
  application:
    name: vote-gateway
  profiles:
    active: dev
#  cloud:
#    gateway:
#      routes:
#      - id: vote-modules-vote
#        uri: lb://vote-modules-vote
#        predicates:
#          - Path=/vote/**
#        filters:
#          - StripPrefix=1
#
#      - id: vote-auth
#        uri: lb://vote-auth
#        predicates:
#          - Path=/auth/**
#        filters:
#          - StripPrefix=1
#
#      - id: vote-modules-permission
#        uri: lb://vote-modules-permission
#        predicates:
#          - Path=/role/**
#        filters:
#          - StripPrefix=1
#
gateway:
  whitelist:
    paths: /auth/auth/register,/auth/auth/login
